//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chatbotrepo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionsTbl
    {
        public int option_id { get; set; }
        public string option { get; set; }
        public int link_id { get; set; }
        public int monitor_id { get; set; }
        public int question_id { get; set; }
    
        public virtual MonitorsTbl MonitorsTbl { get; set; }
        public virtual QuestionsTbl QuestionsTbl { get; set; }
    }
}
